### ISSUE TITLE
`SyntaxError: Unexpected token =>` when running `$ webmention-discovery'

### ISSUE THREAD

**Issue by wholewheattoast** [gobengo/webmention#1]
```
shawns-MacBook-Air:source shawn$ npm install -g webmention
/usr/local/bin/webmention-discovery -> /usr/local/lib/node_modules/webmention/discovery.js
webmention@0.0.0 /usr/local/lib/node_modules/webmention
├── parse-links@0.1.0
├── htmlparser2@3.9.0 (domelementtype@1.3.0, entities@1.1.1, domhandler@2.3.0, domutils@1.5.1, readable-stream@2.0.4)
├── node-fetch@1.3.3 (encoding@0.1.11)
└── trumpet@1.7.2 (inherits@2.0.1, duplexer2@0.0.2, readable-stream@1.1.13, through2@1.1.1, html-tokenize@1.2.5, html-select@2.3.24)
shawns-MacBook-Air:source shawn$ webmention-discovery www.wholewheattoast.com
/usr/local/lib/node_modules/webmention/discovery.js:8
  .then((endpoints) => {
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
shawns-MacBook-Air:source shawn$ webmention-discovery http://www.wholewheattoast.com
/usr/local/lib/node_modules/webmention/discovery.js:8
  .then((endpoints) => {
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
shawns-MacBook-Air:source shawn$ webmention-discovery http://www.wholewheattoast.com/
/usr/local/lib/node_modules/webmention/discovery.js:8
  .then((endpoints) => {
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
shawns-MacBook-Air:source shawn$ webmention-discovery 
/usr/local/lib/node_modules/webmention/discovery.js:8
  .then((endpoints) => {
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
shawns-MacBook-Air:source shawn$ webmention-discovery -help
/usr/local/lib/node_modules/webmention/discovery.js:8
  .then((endpoints) => {
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
shawns-MacBook-Air:source shawn$ 
```

**Comment by gobengo** [comment]
Use node >= 4.0.0

**Comment by wholewheattoast** [comment]
ok after updating node

``````
shawns-MacBook-Air:Documents shawn$ node -v
v5.1.0
shawns-MacBook-Air:Documents shawn$ webmention-discovery http://bengo.is
Error discovering endpoint [TypeError: Method must be a valid HTTP token]
TypeError: Method must be a valid HTTP token
    at new ClientRequest (_http_client.js:74:11)
    at exports.request (http.js:31:10)
    at /usr/local/lib/node_modules/webmention/node_modules/node-fetch/index.js:103:13
    at new Fetch (/usr/local/lib/node_modules/webmention/node_modules/node-fetch/index.js:44:9)
    at Fetch (/usr/local/lib/node_modules/webmention/node_modules/node-fetch/index.js:32:10)
    at discoverFromHEAD (/usr/local/lib/node_modules/webmention/discovery.js:32:10)
    at discover (/usr/local/lib/node_modules/webmention/discovery.js:22:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/webmention/discovery.js:7:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)```
``````

**Comment by gobengo** [comment]
@wholewheattoast I think there was a bug in the original version I npm published (I was scrambling to fix bugs and deploy the api somewhere right before the demo time of indiewebcamp sf).

I just published a 0.0.1, and did a fresh `npm install -g webmention` and it worked for me. I'm thinking it will work for you too after a `npm update -g webmention`

Sorry for the mishap
